### ISSUE TITLE
Can't create control Group 0 : TRM German keyboard

### ISSUE THREAD

**Issue by immoli** [jonnyhweiss/TheCoreConverter#24]
Dear Developers,
Was messing around with TheCore.
I'm nearly Masters now and its quite intuitive to learn.

But i figured out that one cannot create the Control Group 0 by pressing ctrl+shift+0
it doesn't work.
with ctrl+0 i can assign units to this Group but i can not create this group with selected units by using ctrl+shift+0
alt+ctrl+0 works as Camera and it recalls with shift+0

Was searching a way to bind it to another key but thats counterintuitive somehow. Thats why I'm asking now.

Best Regards
immo

Edit : Maybe one need to change the Keybinding to ctrl+shift+"="
Because on the german keybord the shift+0 results in "=" not quite sure about this. (Its not possible to change ingame, is it possible to edit this in the SC2Hotkey file or will Starcraft call this an invalid key ?

**Comment by jonnyhweiss** [comment]
Check out #2 from the FAQ in the TL thread: http://www.teamliquid.net/forum/viewmessage.php?topic_id=341878
