### ISSUE TITLE
question about commands

### ISSUE THREAD

**Issue by mwaschkowski** [jonnyhweiss/TheCoreConverter#27]
Hi,

Is there any file/easy way to get just the commands for one race? I would like to alter a bunch of the protoss keybindings, but don't want to have to go through all the Terran and Zerg bindings to do so, I would just like to have a list of what I need to update/alter for Protoss.

Thank you!

Mark

**Comment by jonnyhweiss** [comment]
You can use the in-game UI to edit just the Protoss commands, then import the changes you made into TheCoreSeed.ini using the InGameGUIImport script (see #4 in the readme).

**Comment by mwaschkowski** [comment]
OK, I'll go that route then.

Thanks

Mark

**Comment by Hancho2009** [comment]
can you close?

**Comment by mwaschkowski** [comment]
Sure thing! :)
